### ISSUE TITLE
good work

### ISSUE THREAD

**Issue by louiswalton** [smilinazzo/timberbrook#7]
thanks for taking time to deliver this.  I had one question about the assumption of results being ordered.   Just wondering how that would change your code if that did not hold true

All the best,
Greg

**Comment by smilinazzo** [comment]
No problem. Was actually a fun project. 

For this, I probably would have had another call in _tools/utils/file_cmp_ to sort the files. Probably ok for a half million lines like we have. But I'd have to think a bit on a better solution if we were talking millions.
