### ISSUE TITLE
Improve duplicate events detection

### ISSUE THREAD

**Issue by dlapin-cribl** [smilinazzo/timberbrook#8]
https://github.com/smilinazzo/timberbrook/blob/master/src/tools/utils.py#L40

This will actually reveal duplicates only under certain circumstances, e.g. duplicate lines will have to be in different target output files. It will miss duplicate lines in case they exist in the same file.

**Comment by smilinazzo** [comment]
I thought about that and then have it total up the number of missing and duplicates. But, in the end, I figured a failure still fails the test. If there were duplicates in the same file (still assuming sorted), the next line read would be the same line. It would read the chunk from the other file (probably passing as it read them), then when it needed the next value that _should_ be in the first file, it would find that duplicate instead, and fail.
